# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a82496e642e9be83216aa3ffe3227bce57d34359ca412e969f21202d8f7b7db09a9e4f11af8fa8b9a1d8bcbc07a726dc0ddb37ecebaeca2283047ac7f3fa59d

test:
  secret_key_base: c65dee31786710685da16b6a49d0000211fd656a7c95e3263554f02a575eb6aded51224e827ab090585f50eb798794a0d85fa446cb473766ab743edecdc33077

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
